KOD DDL: 
-- Generated by Oracle SQL Developer Data Modeler 21.2.0.183.1957
--   at:        2026-01-19 14:48:47 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE budynki (
    id_b  INTEGER NOT NULL,
    nazwa VARCHAR2(25 CHAR) NOT NULL,
    adres VARCHAR2(25 CHAR) NOT NULL
);

ALTER TABLE budynki ADD CONSTRAINT budynki_pk PRIMARY KEY ( id_b );

CREATE TABLE katedry (
    id_kat        INTEGER NOT NULL,
    wydzialy_id_w INTEGER NOT NULL,
    nazwa         VARCHAR2(25 CHAR) NOT NULL,
    kierownik     VARCHAR2(25 CHAR) NOT NULL
);

ALTER TABLE katedry ADD CONSTRAINT katedry_pk PRIMARY KEY ( id_kat );

CREATE TABLE kier_prze (
    kierunki_id_k       INTEGER NOT NULL,
    przedmioty_id_przed INTEGER NOT NULL
);

ALTER TABLE kier_prze ADD CONSTRAINT kier_prze_pk PRIMARY KEY ( przedmioty_id_przed,
                                                                kierunki_id_k );

CREATE TABLE kierunki (
    id_k          INTEGER NOT NULL,
    nazwa         VARCHAR2(25 CHAR) NOT NULL,
    wydzialy_id_w INTEGER NOT NULL,
    stopien       VARCHAR2(25 CHAR) NOT NULL
);

ALTER TABLE kierunki ADD CONSTRAINT kierunki_pk PRIMARY KEY ( id_k );

CREATE TABLE legitymacje (
    id_l          INTEGER NOT NULL,
    data_wydania  DATE NOT NULL,
    data_waznosci DATE NOT NULL,
    studenci_id_s INTEGER NOT NULL
);

CREATE UNIQUE INDEX legitymacje__idx ON
    legitymacje (
        studenci_id_s
    ASC );

ALTER TABLE legitymacje ADD CONSTRAINT legitymacje_pk PRIMARY KEY ( id_l );

CREATE TABLE pracownicy (
    id_prac     INTEGER NOT NULL,
    imie        VARCHAR2(25 CHAR),
    nazwisko    VARCHAR2(35 CHAR) NOT NULL,
    data_zatrud DATE NOT NULL,
    stanowisko  VARCHAR2(20 CHAR),
    pensja      FLOAT(2) NOT NULL
);

ALTER TABLE pracownicy ADD CONSTRAINT pracownicy_pk PRIMARY KEY ( id_prac );

CREATE TABLE prze_sal (
    przedmioty_id_przed INTEGER NOT NULL,
    sale_id_sali        INTEGER NOT NULL
);

CREATE TABLE przedmioty (
    id_przed INTEGER NOT NULL,
    nazwa    VARCHAR2(25 CHAR) NOT NULL,
    ects     INTEGER NOT NULL
);

ALTER TABLE przedmioty ADD CONSTRAINT przedmioty_pk PRIMARY KEY ( id_przed );

CREATE TABLE sale (
    id_sali       INTEGER NOT NULL,
    nazwa         VARCHAR2(20 CHAR) NOT NULL,
    pojemnosc     INTEGER NOT NULL,
    czy_projektor CHAR(1) NOT NULL,
    budynki_id_b  INTEGER NOT NULL
);

ALTER TABLE sale ADD CONSTRAINT sale_pk PRIMARY KEY ( id_sali );

CREATE TABLE studenci (
    id_s          INTEGER NOT NULL,
    imie          VARCHAR2(25 CHAR),
    nazwisko      VARCHAR2(35 CHAR) NOT NULL,
    data_urodz    DATE NOT NULL,
    mail          VARCHAR2(25) NOT NULL,
    kierunki_id_k INTEGER NOT NULL
);

ALTER TABLE studenci ADD CONSTRAINT studenci_pk PRIMARY KEY ( id_s );

CREATE TABLE stypendia (
    id_sty        INTEGER NOT NULL,
    rodzaj        VARCHAR2(20) NOT NULL,
    kwota         FLOAT(2) NOT NULL,
    studenci_id_s INTEGER NOT NULL
);

ALTER TABLE stypendia ADD CONSTRAINT stypendia_pk PRIMARY KEY ( id_sty );

CREATE TABLE wydzialy (
    id_w          INTEGER NOT NULL,
    nazwa         VARCHAR2(25 CHAR) NOT NULL,
    dyrektor_stud VARCHAR2(25 CHAR) NOT NULL
);

ALTER TABLE wydzialy ADD CONSTRAINT wydzialy_pk PRIMARY KEY ( id_w );

CREATE TABLE wykładowcy (
    id_prac        INTEGER NOT NULL,
    stopien        VARCHAR2(25 CHAR) NOT NULL,
    specjalizacja  VARCHAR2(25 CHAR) NOT NULL,
    katedry_id_kat INTEGER
);

ALTER TABLE wykładowcy ADD CONSTRAINT wykładowcy_pk PRIMARY KEY ( id_prac );

ALTER TABLE katedry
    ADD CONSTRAINT katedry_wydzialy_fk FOREIGN KEY ( wydzialy_id_w )
        REFERENCES wydzialy ( id_w );

ALTER TABLE kier_prze
    ADD CONSTRAINT kier_prze_kierunki_fk FOREIGN KEY ( kierunki_id_k )
        REFERENCES kierunki ( id_k );

ALTER TABLE kier_prze
    ADD CONSTRAINT kier_prze_przedmioty_fk FOREIGN KEY ( przedmioty_id_przed )
        REFERENCES przedmioty ( id_przed );

ALTER TABLE kierunki
    ADD CONSTRAINT kierunki_wydzialy_fk FOREIGN KEY ( wydzialy_id_w )
        REFERENCES wydzialy ( id_w );

ALTER TABLE legitymacje
    ADD CONSTRAINT legitymacje_studenci_fk FOREIGN KEY ( studenci_id_s )
        REFERENCES studenci ( id_s );

ALTER TABLE prze_sal
    ADD CONSTRAINT prze_sal_przedmioty_fk FOREIGN KEY ( przedmioty_id_przed )
        REFERENCES przedmioty ( id_przed );

ALTER TABLE prze_sal
    ADD CONSTRAINT prze_sal_sale_fk FOREIGN KEY ( sale_id_sali )
        REFERENCES sale ( id_sali );

ALTER TABLE sale
    ADD CONSTRAINT sale_budynki_fk FOREIGN KEY ( budynki_id_b )
        REFERENCES budynki ( id_b );

ALTER TABLE studenci
    ADD CONSTRAINT studenci_kierunki_fk FOREIGN KEY ( kierunki_id_k )
        REFERENCES kierunki ( id_k );

ALTER TABLE stypendia
    ADD CONSTRAINT stypendia_studenci_fk FOREIGN KEY ( studenci_id_s )
        REFERENCES studenci ( id_s );

ALTER TABLE wykładowcy
    ADD CONSTRAINT wykładowcy_katedry_fk FOREIGN KEY ( katedry_id_kat )
        REFERENCES katedry ( id_kat );

ALTER TABLE wykładowcy
    ADD CONSTRAINT wykładowcy_pracownicy_fk FOREIGN KEY ( id_prac )
        REFERENCES pracownicy ( id_prac );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            13
-- CREATE INDEX                             1
-- ALTER TABLE                             24
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
